server:
  port: ${SERVER_PORT:8080}

spring:
  data:
    mongodb:
      uri: ${MONGO_URI}

app:
  jwt:
    secret: ${APP_JWT_SECRET}
    accessMinutes: 15
    refreshDays: 30
  cors:
    allowedOrigins: ${APP_CORS_ALLOWEDORIGINS:http://localhost:5173}
